// TODO remove pins?
declare namespace pins {
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A0)
    const A0: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A1)
    const A1: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A2)
    const A2: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A3)
    const A3: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A4)
    const A4: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A5)
    const A5: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A6)
    const A6: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A7)
    const A7: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A8)
    const A8: PwmOnlyPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A9)
    const A9: PwmOnlyPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A10)
    const A10: PwmOnlyPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A11)
    const A11: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A12)
    const A12: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_A15)
    const A15: DigitalInOutPin;

    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B0)
    const B0: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B1)
    const B1: PwmPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B2)
    const B2: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B3)
    const B3: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B4)
    const B4: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B5)
    const B5: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B6)
    const B6: PwmOnlyPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B7)
    const B7: PwmOnlyPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B8)
    const B8: PwmOnlyPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B9)
    const B9: PwmOnlyPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B10)
    const B10: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B11)
    const B11: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B12)
    const B12: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B13)
    const B13: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B14)
    const B14: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_B15)
    const B15: DigitalInOutPin;

    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C0)
    const C0: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C1)
    const C1: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C2)
    const C2: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C3)
    const C3: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C4)
    const C4: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C5)
    const C5: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C6)
    const C6: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C7)
    const C7: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C8)
    const C8: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C9)
    const C9: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C10)
    const C10: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C11)
    const C11: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C12)
    const C12: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C13)
    const C13: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C14)
    const C14: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_C15)
    const C15: DigitalInOutPin;

    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_LED)
    const LED: DigitalInOutPin;

    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_LED1)
    const LED1: DigitalInOutPin;

    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_SCK)
    const SCK: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_MISO)
    const MISO: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_MOSI)
    const MOSI: DigitalInOutPin;

    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_SDA)
    const SDA: DigitalInOutPin;
    //% fixedInstance shim=pxt::getPinCfg(CFG_PIN_SCL)
    const SCL: DigitalInOutPin;
}
