namespace config {
    export const PIN_NEOPIXEL = DAL.PC24;
    export const NUM_NEOPIXELS = 1;
    
    //export const PIN_AREF = DAL.PA03;
    export const PIN_A0 = DAL.PA02;
    export const PIN_A1 = DAL.PA05;
    export const PIN_A2 = DAL.PB03;
    export const PIN_A3 = DAL.PC00;
    export const PIN_A4 = DAL.PC01;
    export const PIN_A5 = DAL.PC02;
    export const PIN_A6 = DAL.PC03;
    export const PIN_A7 = DAL.PB04;

    export const PIN_A8 = DAL.PB05;
    export const PIN_A9 = DAL.PB06;
    export const PIN_A10 = DAL.PB07;
    export const PIN_A11 = DAL.PB08;
    export const PIN_A12 = DAL.PB09;
    export const PIN_A13 = DAL.PA04;
    export const PIN_A14 = DAL.PA06;
    export const PIN_A15 = DAL.PA07;

    export const PIN_D0 = DAL.PB25;
    export const PIN_D1 = DAL.PB24;
    export const PIN_D2 = DAL.PC18;
    export const PIN_D3 = DAL.PC19;
    export const PIN_D4 = DAL.PC20;
    export const PIN_D5 = DAL.PC21;
    export const PIN_D6 = DAL.PD20;
    export const PIN_D7 = DAL.PD21;
    export const PIN_D8 = DAL.PB18;
    export const PIN_D9 = DAL.PB02;
    export const PIN_D10 = DAL.PB22;
    export const PIN_D11 = DAL.PB23;
    export const PIN_D12 = DAL.PB00;
    export const PIN_D13 = DAL.PB01;
	
	export const PIN_D14 = DAL.PB16;
	export const PIN_D15 = DAL.PB17;
	export const PIN_D16 = DAL.PC22;
	export const PIN_D17 = DAL.PC23;
	export const PIN_D18 = DAL.PB12;
	export const PIN_D19 = DAL.PB13;
	export const PIN_D20 = DAL.PB20;
	export const PIN_D21 = DAL.PB21;
	export const PIN_D22 = DAL.PD12;
    export const PIN_D23 = DAL.PA15;
    export const PIN_D24 = DAL.PC17;
	export const PIN_D25 = DAL.PC16;
	export const PIN_D26 = DAL.PA12;
	export const PIN_D27 = DAL.PA13;
	export const PIN_D28 = DAL.PA14;
	export const PIN_D29 = DAL.PB19;
	export const PIN_D30 = DAL.PA23;
	export const PIN_D31 = DAL.PA22;
	export const PIN_D32 = DAL.PA21;
	export const PIN_D33 = DAL.PA20;
	export const PIN_D34 = DAL.PA19;
	export const PIN_D35 = DAL.PA18;
	export const PIN_D36 = DAL.PA17;
    export const PIN_D37 = DAL.PA16;
    export const PIN_D38 = DAL.PB15;
    export const PIN_D39 = DAL.PB14;
    export const PIN_D40 = DAL.PC13;
    export const PIN_D41 = DAL.PC12;
    export const PIN_D42 = DAL.PC15;
    export const PIN_D43 = DAL.PC14;
    export const PIN_D44 = DAL.PC11;
    export const PIN_D45 = DAL.PC10;
    export const PIN_D46 = DAL.PC06;
    export const PIN_D47 = DAL.PC07;
    export const PIN_D48 = DAL.PC04;
    export const PIN_D49 = DAL.PC05;
    export const PIN_D50 = DAL.PD11;
    export const PIN_D51 = DAL.PD08;
    export const PIN_D52 = DAL.PD09;
    export const PIN_D53 = DAL.PD10;
	
	export const PIN_LED = PIN_D13; // D13
	export const PIN_RX = PIN_D0; // D0
	export const PIN_TX = PIN_D1; // D1
	export const PIN_MISO = PIN_D50;
    export const PIN_MOSI = PIN_D51;
    export const PIN_SCK = PIN_D52;
    export const PIN_SS = PIN_D53;
	export const PIN_SDA = PIN_D20;
    export const PIN_SCL = PIN_D21;
	export const PIN_RXLED = DAL.PC31;
    export const PIN_TXLED = DAL.PC30;
	
	export const PIN_JACK_TX = PIN_TX;
	export const PIN_JACK_COMMLED = PIN_TXLED;
	
	export const PIN_TX3 = PIN_D14;
    export const PIN_RX3 = PIN_D15;
    export const PIN_TX2 = PIN_D16;
    export const PIN_RX2 = PIN_D17;
    export const PIN_TX1 = PIN_D18;
    export const PIN_RX1 = PIN_D19;
	export const PIN_SCL1 = PIN_D24;
    export const PIN_SDA1 = PIN_D25;
	
	export const PIN_FLASH_MISO = DAL.PA09; // FLASH_IO1
    export const PIN_FLASH_MOSI = DAL.PA08; // FLASH_IO0
    export const PIN_FLASH_SCK = DAL.PB10;
    export const PIN_FLASH_CS = DAL.PB11;
    
    export const PIN_CC_DEN1 = DAL.PA12;
    export const PIN_CC_DEN2 = DAL.PA13;
    export const PIN_CC_CLK = DAL.PA14;
    export const PIN_XCC_CLK = DAL.PB19;
    export const PIN_PCC_D7 = DAL.PA23;
    export const PIN_PCC_D6 = DAL.PA22;
    export const PIN_PCC_D5 = DAL.PA21;
    export const PIN_PCC_D4 = DAL.PA20;
    export const PIN_PCC_D3 = DAL.PA19;  
    export const PIN_PCC_D2 = DAL.PA18;
    export const PIN_PCC_D1 = DAL.PA17;
    export const PIN_PCC_D0 = DAL.PA16;
    export const PIN_PCC_D9 = DAL.PB15;
    export const PIN_PCC_D8 = DAL.PB14;
    export const PIN_PCC_D11 = DAL.PC13;
    export const PIN_PCC_D10 = DAL.PC12;
    export const PIN_PCC_D13 = DAL.PC15;
    export const PIN_PCC_D12 = DAL.PC14;
}
